[project]
name = "rehab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kaggle>=1.8.2",
    "pandas>=2.3.3",
    "pytest>=9.0.1",
]
